### PR TITLE
Update hhp for newer dependencies

### LINKED ISSUE #5: Build failure
```
Preprocessing executable 'hhp' for xmonad-utils-0.1.3.2.1...
[1 of 2] Compiling Utils            ( src/Utils.hs, dist/build/hhp/hhp-tmp/Utils.o )
[2 of 2] Compiling Main             ( src/Hhp.hs, dist/build/hhp/hhp-tmp/Main.o )

src/Hhp.hs:57:3: Not in scope: ‘block’

src/Hhp.hs:71:16: Not in scope: ‘unblock’
Failed to install xmonad-utils-0.1.3.2.1
cabal: Error: some packages failed to install:
xmonad-utils-0.1.3.2.1 failed during the building phase. The exception was:
ExitFailure 1
```

GHC 7.8.2, Cabal 1.20.0.1, Arch Linux

### PR DESCRIPTION
**Pull request by pbrisbin**
- block/unblock deprecated and now removed for mask
- Prelude does not export catch

Fixes #5

### CODE REVIEW

**Comment by LeifW** [comment]
Thanks for fixing this!  Sorry I didn't get to it myself - I'm on an Ubuntu laptop for the time being at my new job, and don't have access to GHC 7.8 right now.
Though, should we leave in the "hiding (catch)" part?  Doesn't seem harmful it it's just a compile-time warning. I've removed it in the past, but someone (I'm assuming on GHC pre-7.6) re-added it in #3.  Otherwise, maybe we should add some restrictions on base versions in the cabal file, and publish a version restricted to the old GHC that we'll not update, and then the new xmonad-utils won't have to worry about backwards compat?

**Comment by pbrisbin** [comment]
Thanks for reviewing! I decided to leave anything like that up to you. I'm not sure at what versions these things changed, I was just following the errors / warnings on my own system (Arch, GHC 7.8).

If you need to add lower version bounds, use CPP to guard on GHC version, or just want to bring the `hiding` back -- anything would be fine with me.

**Comment by LeifW** [comment]
I've got it building across three GHC versions (7.4, 7.6, 7.8) on travis-ci: https://travis-ci.org/LeifW/xmonad-utils
So now we can make changes w/out worrying about breaking it for people.  I'll play around w/ solutions to get this in w/out breaking 7.4 people.

**Comment by LeifW** [comment]
Huh. Looks like it's already broken on 7.4.  Well... no one's complained, so... screw them? :J I'll go ahead and merge this for now, and if any 7.4 people complain, they can use an older version, or we could see about doing something fancier.

**Pull request merged**
